// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Problem struct {
	ID           int64           `json:"id"`
	Title        string          `json:"title"`
	TitleSlug    string          `json:"title_slug"`
	FrontendID   string          `json:"frontend_id"`
	Difficulty   string          `json:"difficulty"`
	Content      sql.NullString  `json:"content"`
	TopicTags    sql.NullString  `json:"topic_tags"`
	CodeSnippets sql.NullString  `json:"code_snippets"`
	IsPaidOnly   sql.NullInt64   `json:"is_paid_only"`
	AcRate       sql.NullFloat64 `json:"ac_rate"`
	Site         sql.NullString  `json:"site"`
	Status       sql.NullString  `json:"status"`
	FetchedAt    sql.NullTime    `json:"fetched_at"`
}

type ProblemTag struct {
	ProblemID sql.NullInt64 `json:"problem_id"`
	Tag       string        `json:"tag"`
}

type ReviewCard struct {
	ProblemID     int64        `json:"problem_id"`
	Due           time.Time    `json:"due"`
	Stability     float64      `json:"stability"`
	Difficulty    float64      `json:"difficulty"`
	ElapsedDays   float64      `json:"elapsed_days"`
	ScheduledDays float64      `json:"scheduled_days"`
	Reps          int64        `json:"reps"`
	Lapses        int64        `json:"lapses"`
	State         int64        `json:"state"`
	LastReview    sql.NullTime `json:"last_review"`
}

type ReviewLog struct {
	ID            int64           `json:"id"`
	ProblemID     sql.NullInt64   `json:"problem_id"`
	Rating        int64           `json:"rating"`
	State         int64           `json:"state"`
	ElapsedDays   sql.NullFloat64 `json:"elapsed_days"`
	ScheduledDays sql.NullFloat64 `json:"scheduled_days"`
	TimeSpentSec  sql.NullInt64   `json:"time_spent_sec"`
	ReviewedAt    sql.NullTime    `json:"reviewed_at"`
}

type StudyPlan struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	IsPredefined sql.NullInt64  `json:"is_predefined"`
	IsActive     sql.NullInt64  `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type StudyPlanProblem struct {
	PlanID      sql.NullInt64  `json:"plan_id"`
	ProblemID   sql.NullInt64  `json:"problem_id"`
	DayNumber   int64          `json:"day_number"`
	TopicGroup  sql.NullString `json:"topic_group"`
	SortOrder   sql.NullInt64  `json:"sort_order"`
	IsCompleted sql.NullInt64  `json:"is_completed"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

type Submission struct {
	ID          int64         `json:"id"`
	ProblemID   sql.NullInt64 `json:"problem_id"`
	Lang        string        `json:"lang"`
	Code        string        `json:"code"`
	Status      string        `json:"status"`
	RuntimeMs   sql.NullInt64 `json:"runtime_ms"`
	MemoryKb    sql.NullInt64 `json:"memory_kb"`
	SubmittedAt sql.NullTime  `json:"submitted_at"`
}
