// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addProblemToPlan = `-- name: AddProblemToPlan :exec
INSERT INTO study_plan_problems (plan_id, problem_id, day_number, topic_group, sort_order)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type AddProblemToPlanParams struct {
	PlanID     sql.NullInt64  `json:"plan_id"`
	ProblemID  sql.NullInt64  `json:"problem_id"`
	DayNumber  int64          `json:"day_number"`
	TopicGroup sql.NullString `json:"topic_group"`
	SortOrder  sql.NullInt64  `json:"sort_order"`
}

func (q *Queries) AddProblemToPlan(ctx context.Context, arg AddProblemToPlanParams) error {
	_, err := q.db.ExecContext(ctx, addProblemToPlan,
		arg.PlanID,
		arg.ProblemID,
		arg.DayNumber,
		arg.TopicGroup,
		arg.SortOrder,
	)
	return err
}

const completePlanProblem = `-- name: CompletePlanProblem :exec
UPDATE study_plan_problems
SET is_completed = 1, completed_at = CURRENT_TIMESTAMP
WHERE plan_id = ? AND problem_id = ?
`

type CompletePlanProblemParams struct {
	PlanID    sql.NullInt64 `json:"plan_id"`
	ProblemID sql.NullInt64 `json:"problem_id"`
}

func (q *Queries) CompletePlanProblem(ctx context.Context, arg CompletePlanProblemParams) error {
	_, err := q.db.ExecContext(ctx, completePlanProblem, arg.PlanID, arg.ProblemID)
	return err
}

const countPlanProgress = `-- name: CountPlanProgress :one
SELECT
    COUNT(*) as total,
    SUM(CASE WHEN is_completed = 1 THEN 1 ELSE 0 END) as completed
FROM study_plan_problems WHERE plan_id = ?
`

type CountPlanProgressRow struct {
	Total     int64           `json:"total"`
	Completed sql.NullFloat64 `json:"completed"`
}

func (q *Queries) CountPlanProgress(ctx context.Context, planID sql.NullInt64) (CountPlanProgressRow, error) {
	row := q.db.QueryRowContext(ctx, countPlanProgress, planID)
	var i CountPlanProgressRow
	err := row.Scan(&i.Total, &i.Completed)
	return i, err
}

const createStudyPlan = `-- name: CreateStudyPlan :one
INSERT INTO study_plans (name, slug, description, is_predefined, is_active)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, slug, description, is_predefined, is_active, created_at
`

type CreateStudyPlanParams struct {
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	IsPredefined sql.NullInt64  `json:"is_predefined"`
	IsActive     sql.NullInt64  `json:"is_active"`
}

func (q *Queries) CreateStudyPlan(ctx context.Context, arg CreateStudyPlanParams) (StudyPlan, error) {
	row := q.db.QueryRowContext(ctx, createStudyPlan,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IsPredefined,
		arg.IsActive,
	)
	var i StudyPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsPredefined,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAllPlans = `-- name: DeactivateAllPlans :exec
UPDATE study_plans SET is_active = 0
`

func (q *Queries) DeactivateAllPlans(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deactivateAllPlans)
	return err
}

const getActivePlan = `-- name: GetActivePlan :one
SELECT id, name, slug, description, is_predefined, is_active, created_at FROM study_plans WHERE is_active = 1 LIMIT 1
`

func (q *Queries) GetActivePlan(ctx context.Context) (StudyPlan, error) {
	row := q.db.QueryRowContext(ctx, getActivePlan)
	var i StudyPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsPredefined,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getStudyPlan = `-- name: GetStudyPlan :one
SELECT id, name, slug, description, is_predefined, is_active, created_at FROM study_plans WHERE id = ? LIMIT 1
`

func (q *Queries) GetStudyPlan(ctx context.Context, id int64) (StudyPlan, error) {
	row := q.db.QueryRowContext(ctx, getStudyPlan, id)
	var i StudyPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsPredefined,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getStudyPlanBySlug = `-- name: GetStudyPlanBySlug :one
SELECT id, name, slug, description, is_predefined, is_active, created_at FROM study_plans WHERE slug = ? LIMIT 1
`

func (q *Queries) GetStudyPlanBySlug(ctx context.Context, slug string) (StudyPlan, error) {
	row := q.db.QueryRowContext(ctx, getStudyPlanBySlug, slug)
	var i StudyPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsPredefined,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listIncompletePlanProblems = `-- name: ListIncompletePlanProblems :many
SELECT spp.plan_id, spp.problem_id, spp.day_number, spp.topic_group, spp.sort_order, spp.is_completed, spp.completed_at, p.title, p.frontend_id, p.difficulty, p.title_slug
FROM study_plan_problems spp
JOIN problems p ON spp.problem_id = p.id
WHERE spp.plan_id = ? AND spp.is_completed = 0
ORDER BY spp.day_number, spp.sort_order
LIMIT ?
`

type ListIncompletePlanProblemsParams struct {
	PlanID sql.NullInt64 `json:"plan_id"`
	Limit  int64         `json:"limit"`
}

type ListIncompletePlanProblemsRow struct {
	PlanID      sql.NullInt64  `json:"plan_id"`
	ProblemID   sql.NullInt64  `json:"problem_id"`
	DayNumber   int64          `json:"day_number"`
	TopicGroup  sql.NullString `json:"topic_group"`
	SortOrder   sql.NullInt64  `json:"sort_order"`
	IsCompleted sql.NullInt64  `json:"is_completed"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	Title       string         `json:"title"`
	FrontendID  string         `json:"frontend_id"`
	Difficulty  string         `json:"difficulty"`
	TitleSlug   string         `json:"title_slug"`
}

func (q *Queries) ListIncompletePlanProblems(ctx context.Context, arg ListIncompletePlanProblemsParams) ([]ListIncompletePlanProblemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncompletePlanProblems, arg.PlanID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncompletePlanProblemsRow{}
	for rows.Next() {
		var i ListIncompletePlanProblemsRow
		if err := rows.Scan(
			&i.PlanID,
			&i.ProblemID,
			&i.DayNumber,
			&i.TopicGroup,
			&i.SortOrder,
			&i.IsCompleted,
			&i.CompletedAt,
			&i.Title,
			&i.FrontendID,
			&i.Difficulty,
			&i.TitleSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanProblems = `-- name: ListPlanProblems :many
SELECT spp.plan_id, spp.problem_id, spp.day_number, spp.topic_group, spp.sort_order, spp.is_completed, spp.completed_at, p.title, p.frontend_id, p.difficulty, p.title_slug
FROM study_plan_problems spp
JOIN problems p ON spp.problem_id = p.id
WHERE spp.plan_id = ?
ORDER BY spp.day_number, spp.sort_order
`

type ListPlanProblemsRow struct {
	PlanID      sql.NullInt64  `json:"plan_id"`
	ProblemID   sql.NullInt64  `json:"problem_id"`
	DayNumber   int64          `json:"day_number"`
	TopicGroup  sql.NullString `json:"topic_group"`
	SortOrder   sql.NullInt64  `json:"sort_order"`
	IsCompleted sql.NullInt64  `json:"is_completed"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	Title       string         `json:"title"`
	FrontendID  string         `json:"frontend_id"`
	Difficulty  string         `json:"difficulty"`
	TitleSlug   string         `json:"title_slug"`
}

func (q *Queries) ListPlanProblems(ctx context.Context, planID sql.NullInt64) ([]ListPlanProblemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlanProblems, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanProblemsRow{}
	for rows.Next() {
		var i ListPlanProblemsRow
		if err := rows.Scan(
			&i.PlanID,
			&i.ProblemID,
			&i.DayNumber,
			&i.TopicGroup,
			&i.SortOrder,
			&i.IsCompleted,
			&i.CompletedAt,
			&i.Title,
			&i.FrontendID,
			&i.Difficulty,
			&i.TitleSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudyPlans = `-- name: ListStudyPlans :many
SELECT id, name, slug, description, is_predefined, is_active, created_at FROM study_plans ORDER BY is_active DESC, created_at DESC
`

func (q *Queries) ListStudyPlans(ctx context.Context) ([]StudyPlan, error) {
	rows, err := q.db.QueryContext(ctx, listStudyPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudyPlan{}
	for rows.Next() {
		var i StudyPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsPredefined,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActivePlan = `-- name: SetActivePlan :exec
UPDATE study_plans SET is_active = CASE WHEN id = ? THEN 1 ELSE 0 END
`

func (q *Queries) SetActivePlan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setActivePlan, id)
	return err
}
