// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problems.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countProblems = `-- name: CountProblems :one
SELECT COUNT(*) FROM problems WHERE site = ?
`

func (q *Queries) CountProblems(ctx context.Context, site sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProblems, site)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProblemsByDifficulty = `-- name: CountProblemsByDifficulty :one
SELECT COUNT(*) FROM problems WHERE site = ? AND difficulty = ?
`

type CountProblemsByDifficultyParams struct {
	Site       sql.NullString `json:"site"`
	Difficulty string         `json:"difficulty"`
}

func (q *Queries) CountProblemsByDifficulty(ctx context.Context, arg CountProblemsByDifficultyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProblemsByDifficulty, arg.Site, arg.Difficulty)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProblemsByDifficultyAll = `-- name: CountProblemsByDifficultyAll :many
SELECT difficulty, COUNT(*) as cnt FROM problems WHERE site = ? GROUP BY difficulty
`

type CountProblemsByDifficultyAllRow struct {
	Difficulty string `json:"difficulty"`
	Cnt        int64  `json:"cnt"`
}

func (q *Queries) CountProblemsByDifficultyAll(ctx context.Context, site sql.NullString) ([]CountProblemsByDifficultyAllRow, error) {
	rows, err := q.db.QueryContext(ctx, countProblemsByDifficultyAll, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountProblemsByDifficultyAllRow{}
	for rows.Next() {
		var i CountProblemsByDifficultyAllRow
		if err := rows.Scan(&i.Difficulty, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSolvedByDifficulty = `-- name: CountSolvedByDifficulty :many
SELECT difficulty, COUNT(*) as cnt FROM problems WHERE status = 'ac' AND site = ? GROUP BY difficulty
`

type CountSolvedByDifficultyRow struct {
	Difficulty string `json:"difficulty"`
	Cnt        int64  `json:"cnt"`
}

func (q *Queries) CountSolvedByDifficulty(ctx context.Context, site sql.NullString) ([]CountSolvedByDifficultyRow, error) {
	rows, err := q.db.QueryContext(ctx, countSolvedByDifficulty, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSolvedByDifficultyRow{}
	for rows.Next() {
		var i CountSolvedByDifficultyRow
		if err := rows.Scan(&i.Difficulty, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSolvedProblems = `-- name: CountSolvedProblems :one
SELECT COUNT(*) FROM problems WHERE status = 'ac' AND site = ?
`

func (q *Queries) CountSolvedProblems(ctx context.Context, site sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSolvedProblems, site)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProblem = `-- name: GetProblem :one
SELECT id, title, title_slug, frontend_id, difficulty, content, topic_tags, code_snippets, is_paid_only, ac_rate, site, status, fetched_at FROM problems WHERE id = ? LIMIT 1
`

func (q *Queries) GetProblem(ctx context.Context, id int64) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblem, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleSlug,
		&i.FrontendID,
		&i.Difficulty,
		&i.Content,
		&i.TopicTags,
		&i.CodeSnippets,
		&i.IsPaidOnly,
		&i.AcRate,
		&i.Site,
		&i.Status,
		&i.FetchedAt,
	)
	return i, err
}

const getProblemBySlug = `-- name: GetProblemBySlug :one
SELECT id, title, title_slug, frontend_id, difficulty, content, topic_tags, code_snippets, is_paid_only, ac_rate, site, status, fetched_at FROM problems WHERE title_slug = ? LIMIT 1
`

func (q *Queries) GetProblemBySlug(ctx context.Context, titleSlug string) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblemBySlug, titleSlug)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleSlug,
		&i.FrontendID,
		&i.Difficulty,
		&i.Content,
		&i.TopicTags,
		&i.CodeSnippets,
		&i.IsPaidOnly,
		&i.AcRate,
		&i.Site,
		&i.Status,
		&i.FetchedAt,
	)
	return i, err
}

const listProblems = `-- name: ListProblems :many
SELECT id, title, title_slug, frontend_id, difficulty, content, topic_tags, code_snippets, is_paid_only, ac_rate, site, status, fetched_at FROM problems WHERE site = ? ORDER BY CAST(frontend_id AS INTEGER)
`

func (q *Queries) ListProblems(ctx context.Context, site sql.NullString) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, listProblems, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleSlug,
			&i.FrontendID,
			&i.Difficulty,
			&i.Content,
			&i.TopicTags,
			&i.CodeSnippets,
			&i.IsPaidOnly,
			&i.AcRate,
			&i.Site,
			&i.Status,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemsByDifficulty = `-- name: ListProblemsByDifficulty :many
SELECT id, title, title_slug, frontend_id, difficulty, content, topic_tags, code_snippets, is_paid_only, ac_rate, site, status, fetched_at FROM problems WHERE site = ? AND difficulty = ? ORDER BY CAST(frontend_id AS INTEGER)
`

type ListProblemsByDifficultyParams struct {
	Site       sql.NullString `json:"site"`
	Difficulty string         `json:"difficulty"`
}

func (q *Queries) ListProblemsByDifficulty(ctx context.Context, arg ListProblemsByDifficultyParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, listProblemsByDifficulty, arg.Site, arg.Difficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleSlug,
			&i.FrontendID,
			&i.Difficulty,
			&i.Content,
			&i.TopicTags,
			&i.CodeSnippets,
			&i.IsPaidOnly,
			&i.AcRate,
			&i.Site,
			&i.Status,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemsByTag = `-- name: ListProblemsByTag :many
SELECT p.id, p.title, p.title_slug, p.frontend_id, p.difficulty, p.content, p.topic_tags, p.code_snippets, p.is_paid_only, p.ac_rate, p.site, p.status, p.fetched_at FROM problems p
JOIN problem_tags pt ON p.id = pt.problem_id
WHERE pt.tag = ? AND p.site = ?
ORDER BY CAST(p.frontend_id AS INTEGER)
`

type ListProblemsByTagParams struct {
	Tag  string         `json:"tag"`
	Site sql.NullString `json:"site"`
}

func (q *Queries) ListProblemsByTag(ctx context.Context, arg ListProblemsByTagParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, listProblemsByTag, arg.Tag, arg.Site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleSlug,
			&i.FrontendID,
			&i.Difficulty,
			&i.Content,
			&i.TopicTags,
			&i.CodeSnippets,
			&i.IsPaidOnly,
			&i.AcRate,
			&i.Site,
			&i.Status,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT tag, COUNT(*) as cnt FROM problem_tags GROUP BY tag ORDER BY cnt DESC
`

type ListTagsRow struct {
	Tag string `json:"tag"`
	Cnt int64  `json:"cnt"`
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.Tag, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProblems = `-- name: SearchProblems :many
SELECT id, title, title_slug, frontend_id, difficulty, content, topic_tags, code_snippets, is_paid_only, ac_rate, site, status, fetched_at FROM problems
WHERE site = ? AND (title LIKE '%' || ? || '%' OR frontend_id = ?)
ORDER BY CAST(frontend_id AS INTEGER)
LIMIT 50
`

type SearchProblemsParams struct {
	Site       sql.NullString `json:"site"`
	Column2    sql.NullString `json:"column_2"`
	FrontendID string         `json:"frontend_id"`
}

func (q *Queries) SearchProblems(ctx context.Context, arg SearchProblemsParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, searchProblems, arg.Site, arg.Column2, arg.FrontendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleSlug,
			&i.FrontendID,
			&i.Difficulty,
			&i.Content,
			&i.TopicTags,
			&i.CodeSnippets,
			&i.IsPaidOnly,
			&i.AcRate,
			&i.Site,
			&i.Status,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProblemStatus = `-- name: UpdateProblemStatus :exec
UPDATE problems SET status = ? WHERE title_slug = ?
`

type UpdateProblemStatusParams struct {
	Status    sql.NullString `json:"status"`
	TitleSlug string         `json:"title_slug"`
}

func (q *Queries) UpdateProblemStatus(ctx context.Context, arg UpdateProblemStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProblemStatus, arg.Status, arg.TitleSlug)
	return err
}

const upsertProblem = `-- name: UpsertProblem :exec
INSERT INTO problems (id, title, title_slug, frontend_id, difficulty, content, topic_tags, code_snippets, is_paid_only, ac_rate, site, status, fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(title_slug) DO UPDATE SET
    title = excluded.title,
    frontend_id = excluded.frontend_id,
    difficulty = excluded.difficulty,
    content = excluded.content,
    topic_tags = excluded.topic_tags,
    code_snippets = excluded.code_snippets,
    is_paid_only = excluded.is_paid_only,
    ac_rate = excluded.ac_rate,
    status = COALESCE(excluded.status, problems.status),
    fetched_at = CURRENT_TIMESTAMP
`

type UpsertProblemParams struct {
	ID           int64           `json:"id"`
	Title        string          `json:"title"`
	TitleSlug    string          `json:"title_slug"`
	FrontendID   string          `json:"frontend_id"`
	Difficulty   string          `json:"difficulty"`
	Content      sql.NullString  `json:"content"`
	TopicTags    sql.NullString  `json:"topic_tags"`
	CodeSnippets sql.NullString  `json:"code_snippets"`
	IsPaidOnly   sql.NullInt64   `json:"is_paid_only"`
	AcRate       sql.NullFloat64 `json:"ac_rate"`
	Site         sql.NullString  `json:"site"`
	Status       sql.NullString  `json:"status"`
}

func (q *Queries) UpsertProblem(ctx context.Context, arg UpsertProblemParams) error {
	_, err := q.db.ExecContext(ctx, upsertProblem,
		arg.ID,
		arg.Title,
		arg.TitleSlug,
		arg.FrontendID,
		arg.Difficulty,
		arg.Content,
		arg.TopicTags,
		arg.CodeSnippets,
		arg.IsPaidOnly,
		arg.AcRate,
		arg.Site,
		arg.Status,
	)
	return err
}

const upsertProblemTag = `-- name: UpsertProblemTag :exec
INSERT INTO problem_tags (problem_id, tag) VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type UpsertProblemTagParams struct {
	ProblemID sql.NullInt64 `json:"problem_id"`
	Tag       string        `json:"tag"`
}

func (q *Queries) UpsertProblemTag(ctx context.Context, arg UpsertProblemTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertProblemTag, arg.ProblemID, arg.Tag)
	return err
}
