// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countDueReviewCards = `-- name: CountDueReviewCards :one
SELECT COUNT(*) FROM review_cards WHERE due <= ?
`

func (q *Queries) CountDueReviewCards(ctx context.Context, due time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDueReviewCards, due)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsToday = `-- name: CountReviewsToday :one
SELECT COUNT(*) FROM review_logs WHERE DATE(reviewed_at) = DATE('now')
`

func (q *Queries) CountReviewsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReviewLog = `-- name: CreateReviewLog :exec
INSERT INTO review_logs (problem_id, rating, state, elapsed_days, scheduled_days, time_spent_sec)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateReviewLogParams struct {
	ProblemID     sql.NullInt64   `json:"problem_id"`
	Rating        int64           `json:"rating"`
	State         int64           `json:"state"`
	ElapsedDays   sql.NullFloat64 `json:"elapsed_days"`
	ScheduledDays sql.NullFloat64 `json:"scheduled_days"`
	TimeSpentSec  sql.NullInt64   `json:"time_spent_sec"`
}

func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) error {
	_, err := q.db.ExecContext(ctx, createReviewLog,
		arg.ProblemID,
		arg.Rating,
		arg.State,
		arg.ElapsedDays,
		arg.ScheduledDays,
		arg.TimeSpentSec,
	)
	return err
}

const getReviewCard = `-- name: GetReviewCard :one
SELECT problem_id, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, state, last_review FROM review_cards WHERE problem_id = ? LIMIT 1
`

func (q *Queries) GetReviewCard(ctx context.Context, problemID int64) (ReviewCard, error) {
	row := q.db.QueryRowContext(ctx, getReviewCard, problemID)
	var i ReviewCard
	err := row.Scan(
		&i.ProblemID,
		&i.Due,
		&i.Stability,
		&i.Difficulty,
		&i.ElapsedDays,
		&i.ScheduledDays,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.LastReview,
	)
	return i, err
}

const listDueReviewCards = `-- name: ListDueReviewCards :many
SELECT rc.problem_id, rc.due, rc.stability, rc.difficulty, rc.elapsed_days, rc.scheduled_days, rc.reps, rc.lapses, rc.state, rc.last_review, p.title, p.frontend_id, p.difficulty as prob_difficulty, p.title_slug
FROM review_cards rc
JOIN problems p ON rc.problem_id = p.id
WHERE rc.due <= ?
ORDER BY rc.due ASC
`

type ListDueReviewCardsRow struct {
	ProblemID      int64        `json:"problem_id"`
	Due            time.Time    `json:"due"`
	Stability      float64      `json:"stability"`
	Difficulty     float64      `json:"difficulty"`
	ElapsedDays    float64      `json:"elapsed_days"`
	ScheduledDays  float64      `json:"scheduled_days"`
	Reps           int64        `json:"reps"`
	Lapses         int64        `json:"lapses"`
	State          int64        `json:"state"`
	LastReview     sql.NullTime `json:"last_review"`
	Title          string       `json:"title"`
	FrontendID     string       `json:"frontend_id"`
	ProbDifficulty string       `json:"prob_difficulty"`
	TitleSlug      string       `json:"title_slug"`
}

func (q *Queries) ListDueReviewCards(ctx context.Context, due time.Time) ([]ListDueReviewCardsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueReviewCards, due)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueReviewCardsRow{}
	for rows.Next() {
		var i ListDueReviewCardsRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
			&i.Title,
			&i.FrontendID,
			&i.ProbDifficulty,
			&i.TitleSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewLogsByProblem = `-- name: ListReviewLogsByProblem :many
SELECT id, problem_id, rating, state, elapsed_days, scheduled_days, time_spent_sec, reviewed_at FROM review_logs WHERE problem_id = ? ORDER BY reviewed_at DESC
`

func (q *Queries) ListReviewLogsByProblem(ctx context.Context, problemID sql.NullInt64) ([]ReviewLog, error) {
	rows, err := q.db.QueryContext(ctx, listReviewLogsByProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewLog{}
	for rows.Next() {
		var i ReviewLog
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Rating,
			&i.State,
			&i.ElapsedDays,
			&i.ScheduledDays,
			&i.TimeSpentSec,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReviewCard = `-- name: UpsertReviewCard :exec
INSERT INTO review_cards (problem_id, due, stability, difficulty, elapsed_days, scheduled_days, reps, lapses, state, last_review)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(problem_id) DO UPDATE SET
    due = excluded.due,
    stability = excluded.stability,
    difficulty = excluded.difficulty,
    elapsed_days = excluded.elapsed_days,
    scheduled_days = excluded.scheduled_days,
    reps = excluded.reps,
    lapses = excluded.lapses,
    state = excluded.state,
    last_review = excluded.last_review
`

type UpsertReviewCardParams struct {
	ProblemID     int64        `json:"problem_id"`
	Due           time.Time    `json:"due"`
	Stability     float64      `json:"stability"`
	Difficulty    float64      `json:"difficulty"`
	ElapsedDays   float64      `json:"elapsed_days"`
	ScheduledDays float64      `json:"scheduled_days"`
	Reps          int64        `json:"reps"`
	Lapses        int64        `json:"lapses"`
	State         int64        `json:"state"`
	LastReview    sql.NullTime `json:"last_review"`
}

func (q *Queries) UpsertReviewCard(ctx context.Context, arg UpsertReviewCardParams) error {
	_, err := q.db.ExecContext(ctx, upsertReviewCard,
		arg.ProblemID,
		arg.Due,
		arg.Stability,
		arg.Difficulty,
		arg.ElapsedDays,
		arg.ScheduledDays,
		arg.Reps,
		arg.Lapses,
		arg.State,
		arg.LastReview,
	)
	return err
}
