// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAcceptedByDifficulty = `-- name: CountAcceptedByDifficulty :many
SELECT p.difficulty, COUNT(DISTINCT s.problem_id) as cnt
FROM submissions s
JOIN problems p ON s.problem_id = p.id
WHERE s.status = 'Accepted'
GROUP BY p.difficulty
`

type CountAcceptedByDifficultyRow struct {
	Difficulty string `json:"difficulty"`
	Cnt        int64  `json:"cnt"`
}

func (q *Queries) CountAcceptedByDifficulty(ctx context.Context) ([]CountAcceptedByDifficultyRow, error) {
	rows, err := q.db.QueryContext(ctx, countAcceptedByDifficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAcceptedByDifficultyRow{}
	for rows.Next() {
		var i CountAcceptedByDifficultyRow
		if err := rows.Scan(&i.Difficulty, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAcceptedProblems = `-- name: CountAcceptedProblems :one
SELECT COUNT(DISTINCT problem_id) FROM submissions WHERE status = 'Accepted'
`

func (q *Queries) CountAcceptedProblems(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAcceptedProblems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubmission = `-- name: CreateSubmission :exec
INSERT INTO submissions (problem_id, lang, code, status, runtime_ms, memory_kb)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSubmissionParams struct {
	ProblemID sql.NullInt64 `json:"problem_id"`
	Lang      string        `json:"lang"`
	Code      string        `json:"code"`
	Status    string        `json:"status"`
	RuntimeMs sql.NullInt64 `json:"runtime_ms"`
	MemoryKb  sql.NullInt64 `json:"memory_kb"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, createSubmission,
		arg.ProblemID,
		arg.Lang,
		arg.Code,
		arg.Status,
		arg.RuntimeMs,
		arg.MemoryKb,
	)
	return err
}

const listSubmissionsByProblem = `-- name: ListSubmissionsByProblem :many
SELECT id, problem_id, lang, code, status, runtime_ms, memory_kb, submitted_at FROM submissions WHERE problem_id = ? ORDER BY submitted_at DESC
`

func (q *Queries) ListSubmissionsByProblem(ctx context.Context, problemID sql.NullInt64) ([]Submission, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsByProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Lang,
			&i.Code,
			&i.Status,
			&i.RuntimeMs,
			&i.MemoryKb,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
